spring.application.name: spring-fileupload
spring.output.ansi.enabled: always
aws:
  region: ${AWS_S3_REGION:APAC}
  access-key: ${AWS_ACCESS_KEY:YOUR_AWS_ACCESS_KEY}
  access-secret: ${AWS_SECRET_KEY:YOUR_AWS_SECRET_KEY}
  bucket-name: ${AWS_S3_BUCKET:jvmid-dev}
  endpoint-url: ${AWS_S3_ENDPOINT_URL:YOUR_AWS_S3_ENDPOINT_URL}
